TODO:

Choose just one caption for each image, or keep them all
Field boosting is to be performed in the hybrid-search part

For the cross modal search, the image embedding has to saved once, so the captions should either be collected in the same document with their respective embeddings or only one caption is kept obtaining effectively only one caption per image and vice versa.

## Text-based Search

In [1]:
from dotenv import load_dotenv
import os

load_dotenv()

OPENSEARCH_USER = os.getenv("OPENSEARCH_USER")
OPENSEARCH_PASSWORD = os.getenv("OPENSEARCH_PASSWORD")
OPENSEARCH_HOST = os.getenv("OPENSEARCH_HOST")
OPENSEARCH_PORT = os.getenv("OPENSEARCH_PORT")

In [2]:
import pprint as pp
from opensearchpy import OpenSearch
from opensearchpy import helpers

index_name = OPENSEARCH_USER + '_project'
# Create the client with SSL/TLS enabled, but hostname verification disabled.
client = OpenSearch(
    hosts = [{'host': OPENSEARCH_HOST, 'port': OPENSEARCH_PORT}],
    http_compress = True, # enables gzip compression for request bodies
    http_auth = (OPENSEARCH_USER, OPENSEARCH_PASSWORD),
    use_ssl = True,
    url_prefix = 'opensearch_v3',
    verify_certs = False,
    ssl_assert_hostname = False,
    ssl_show_warn = False
)

if client.indices.exists(index=index_name):

    resp = client.indices.open(index=index_name)
    print(resp)

    print('\n----------------------------------------------------------------------------------- INDEX SETTINGS')
    settings = client.indices.get_settings(index=index_name)
    pp.pprint(settings)

    print('\n----------------------------------------------------------------------------------- INDEX MAPPINGS')
    mappings = client.indices.get_mapping(index=index_name)
    pp.pprint(mappings)

    print('\n----------------------------------------------------------------------------------- INDEX #DOCs')
    print(client.count(index=index_name))
else:
    print("Index does not exist.")

{'acknowledged': True, 'shards_acknowledged': True}

----------------------------------------------------------------------------------- INDEX SETTINGS
{'uservl07_project': {'settings': {'index': {'creation_date': '1774886704756',
                                             'knn': 'true',
                                             'knn.derived_source': {'enabled': 'true'},
                                             'number_of_replicas': '0',
                                             'number_of_shards': '4',
                                             'provided_name': 'uservl07_project',
                                             'refresh_interval': '1s',
                                             'replication': {'type': 'DOCUMENT'},
                                             'similarity': {'bm25-0-75': {'b': '0.75',
                                                                          'k1': '0.0',
                                                                          'type': 'BM25'},
                                                            'bm25-12-0': {'b': '0.0',
                                                                          'k1': '1.2',
                                                                          'type': 'BM25'},
                                                            'bm25-20-75': {'b': '0.75',
                                                                           'k1': '2.0',
                                                                           'type': 'BM25'}},
                                             'uuid': 'pHoPXfebTWaZaMLUYWzvcA',
                                             'version': {'created': '137217827'}}}}}

----------------------------------------------------------------------------------- INDEX MAPPINGS
{'uservl07_project': {'mappings': {'dynamic': 'strict',
                                   'properties': {'BGE_embedding': {'dimension': 384,
                                                                    'method': {'engine': 'faiss',
                                                                               'name': 'hnsw',
                                                                               'parameters': {'ef_construction': 256,
                                                                                              'm': 48},
                                                                               'space_type': 'innerproduct'},
                                                                    'type': 'knn_vector'},
                                                  'SBERT_embedding': {'dimension': 768,
                                                                      'method': {'engine': 'faiss',
                                                                                 'name': 'hnsw',
                                                                                 'parameters': {'ef_construction': 256,
                                                                                                'm': 48},
                                                                                 'space_type': 'innerproduct'},
                                                                      'type': 'knn_vector'},
                                                  'caption': {'analyzer': 'standard',
                                                              'fields': {'bm25_0_75': {'analyzer': 'standard',
                                                                                       'similarity': 'bm25-0-75',
                                                                                       'type': 'text'},
                                                                         'bm25_12_0': {'analyzer': 'standard',
                                                                                       'similarity': 'bm25-12-0',
                                                                                       'type': 'text'},
                                                                         'bm25_20_75': {'analyzer': 'standard',
                                                                                        'similarity': 'bm25-20-75',
                                                                                        'type': 'text'}},
                                                              'similarity': 'BM25',
                                                              'type': 'text'},
                                                  'categories': {'type': 'keyword'},
                                                  'height': {'type': 'integer'},
                                                  'image_id': {'type': 'keyword'},
                                                  'width': {'type': 'integer'}}}}}

----------------------------------------------------------------------------------- INDEX #DOCs
{'count': 25010, '_shards': {'total': 4, 'successful': 4, 'skipped': 0, 'failed': 0}}

In [3]:
from datasets import load_dataset
import aiohttp

ds = load_dataset("HuggingFaceM4/COCO", split="validation",
                  storage_options={'client_kwargs': {'timeout': aiohttp.ClientTimeout(total=36000)}}
                  )
print(ds.column_names)
pp.pprint(ds[0])
print(ds[0]['sentences']['raw'])
print(ds[0]['image'].width)

['image', 'filepath', 'sentids', 'filename', 'imgid', 'split', 'sentences', 'cocoid']
{'cocoid': 184613,
 'filename': 'COCO_val2014_000000184613.jpg',
 'filepath': 'COCO_val2014_000000184613.jpg',
 'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=500x336 at 0x140D0EED0>,
 'imgid': 2,
 'sentences': {'imgid': 2,
               'raw': 'A child holding a flowered umbrella and petting a yak.',
               'sentid': 474921,
               'tokens': ['a',
                          'child',
                          'holding',
                          'a',
                          'flowered',
                          'umbrella',
                          'and',
                          'petting',
                          'a',
                          'yak']},
 'sentids': [474921, 479322, 479334, 481560, 483594],
 'split': 'val'}
A child holding a flowered umbrella and petting a yak.
500

Set up an OpenSearch index and define mappings for image identifiers,
captions, and COCO metadata (categories, image dimensions).

In [4]:
#Delete index if necessary

pp.pprint(client.indices.delete(index=index_name))

{'acknowledged': True}

In [5]:
index_body = {
   "settings":{
      "index":{
         "number_of_replicas":0,
         "number_of_shards":4,
         "refresh_interval":"-1",
         "knn":"true"
      },
      "similarity":{
          "bm25-20-75":{
              "type":"BM25",
              "k1":2.0,
              "b":0.75
          },
          "bm25-12-0":{
              "type":"BM25",
              "k1":1.2,
              "b":0.0
          },
          "bm25-0-75":{
              "type":"BM25",
              "k1":0.0,
              "b":0.75
          }

      }
   },
   "mappings":{
       "dynamic":      "strict",
       "properties":{
            #"_id": { "type": "keyword"},
            "image_id": { "type": "keyword"},
            "caption": { 
                "type": "text",
                "analyzer": "standard",
                "similarity":"BM25",
                "fields":{
                    "bm25_20_75": {
                        "type": "text",
                        "analyzer": "standard",
                        "similarity":"bm25-20-75"
                    },
                    "bm25_12_0": {
                        "type": "text",
                        "analyzer": "standard",
                        "similarity":"bm25-12-0"
                    },
                    "bm25_0_75": {
                        "type": "text",
                        "analyzer": "standard",
                        "similarity":"bm25-0-75"
                     }
                  },
            },
            "categories": { "type": "keyword"},
            "width": { "type": "integer"},
            "height": { "type": "integer"},

            "SBERT_embedding": {
                "type":"knn_vector",
                "dimension": 768,
                "method":{
                    "name":"hnsw",
                    "space_type":"innerproduct",
                    "engine":"faiss",
                    "parameters":{
                        "ef_construction":256,
                        "m":48
                    }
                },
            },

            "BGE_embedding": {
                "type":"knn_vector",
                "dimension": 384,
                "method":{
                    "name":"hnsw",
                    "space_type":"innerproduct",
                    "engine":"faiss",
                    "parameters":{
                        "ef_construction":256,
                        "m":48
                    }
                }
            }
      }
   }
}

if client.indices.exists(index=index_name):
    print("Index already existed. Nothing to be done.")
else:        
    response = client.indices.create(index=index_name, body=index_body)
    print('\nCreating index:')
    print(response)

Creating index:
{'acknowledged': True, 'shards_acknowledged': True, 'index': 'uservl07_project'}

Load dataset captions in index

In [ ]:
def index_data(client, index_name, dataset):
    actions= []
    inserted_imgids = set()
    for i,item in enumerate(dataset):
        if item['sentences']['imgid'] in inserted_imgids:
            continue
        action={
            "_id":item['sentences']['sentid'],
            "image_id":item['sentences']['imgid'],
            "caption":item['sentences']['raw'],
            #"categories":
            "width":item['image'].width,
            "height":item['image'].height
        }
        actions.append(action)
        inserted_imgids.add(item['sentences']['imgid'])
        if len(actions) == 1000:
            helpers.bulk(client, actions, index=index_name)
            print(f"Indexed {i+1} documents")
            actions = []
    if actions:
        helpers.bulk(client, actions, index=index_name)
        print(f"Indexed {len(dataset)} documents in total")
count = client.count(index=index_name)
print(count['count'])

if count['count'] == 0:
    index_data(client, index_name, ds)
else:
    print("Index already contains documents. Nothing to be done.")

0
Indexed 4998 documents
Indexed 9999 documents
Indexed 15002 documents
Indexed 20006 documents
Indexed 25006 documents

In [7]:
client.indices.put_settings(index=index_name, body={"index": {"refresh_interval": "1s"}}) #set refresh interval to 1s to make all operations available for search after 1s
client.indices.refresh(index=index_name) #refresh immediately

{'_shards': {'total': 4, 'successful': 4, 'failed': 0}}

In [8]:

count = client.count(index=index_name)
print(count['count'])

# check a random document
result = client.search(
    index=index_name,
    body={"query": {"match_all": {}}, "size": 1}
)
print(result['hits']['hits'][0]['_source'])

5000
{'image_id': 2, 'caption': 'A child holding a flowered umbrella and petting a yak.', 'width': 500, 'height': 336}

Perform the same query computing similarity with BM25 with different parameters.
For field boosting, idea is to use another field, but the dataset doesn't have a categories objects

In [9]:
query_txt = ds[0]['sentences']['raw']


bm25_fields = ["caption", "caption.bm25_20_75", "caption.bm25_12_0", "caption.bm25_0_75"]

for field in bm25_fields:
    query ={
        "size": 10,
        "query": {
            "match": {
                field: {
                    "query": query_txt
                }
            }
        }
    }
    response = client.search(body=query, index=index_name)
    #pp.pprint(response)
    print(f'\nSearch results for field "{field}":')
    for hit in response['hits']['hits']:
        print(f"Score: {hit['_score']:3.4f}, Doc ID: {hit['_id']}, Image ID: {hit['_source']['image_id']}, Caption: {hit['_source']['caption']}")

Search results for field "caption":
Score: 15.1620, Doc ID: 474921, Image ID: 2, Caption: A child holding a flowered umbrella and petting a yak.
Score: 5.4905, Doc ID: 192463, Image ID: 33253, Caption: a close up of a child holding a closed umbrella
Score: 4.6502, Doc ID: 402111, Image ID: 7647, Caption: a woman and a child holding umbrellas and smiling
Score: 4.3947, Doc ID: 373329, Image ID: 8726, Caption: A child, wearing a cat costume and umbrella, stands before a brick building.
Score: 4.2200, Doc ID: 403240, Image ID: 31747, Caption: A man in shirt and tie holding an umbrella.
Score: 3.9660, Doc ID: 184436, Image ID: 25158, Caption: A young child is holding a blue skateboard.
Score: 3.9541, Doc ID: 488669, Image ID: 6873, Caption: An adult standing holding surfboard and a child kneeling by water.
Score: 3.8189, Doc ID: 207678, Image ID: 27267, Caption: A woman holding a child on a skateboard.
Score: 3.7955, Doc ID: 717298, Image ID: 22998, Caption: A man holding an umbrella in a  hallway.
Score: 3.7042, Doc ID: 268757, Image ID: 39202, Caption: A man holding a bottle and a group of people near an umbrella.

Search results for field "caption.bm25_20_75":
Score: 11.1913, Doc ID: 474921, Image ID: 2, Caption: A child holding a flowered umbrella and petting a yak.
Score: 4.0626, Doc ID: 192463, Image ID: 33253, Caption: a close up of a child holding a closed umbrella
Score: 3.5388, Doc ID: 402111, Image ID: 7647, Caption: a woman and a child holding umbrellas and smiling
Score: 3.1779, Doc ID: 373329, Image ID: 8726, Caption: A child, wearing a cat costume and umbrella, stands before a brick building.
Score: 3.1380, Doc ID: 403240, Image ID: 31747, Caption: A man in shirt and tie holding an umbrella.
Score: 2.9926, Doc ID: 184436, Image ID: 25158, Caption: A young child is holding a blue skateboard.
Score: 2.8898, Doc ID: 207678, Image ID: 27267, Caption: A woman holding a child on a skateboard.
Score: 2.8877, Doc ID: 488669, Image ID: 6873, Caption: An adult standing holding surfboard and a child kneeling by water.
Score: 2.8624, Doc ID: 717298, Image ID: 22998, Caption: A man holding an umbrella in a  hallway.
Score: 2.7559, Doc ID: 44102, Image ID: 5578, Caption: a small child holding on to his luggage

Search results for field "caption.bm25_12_0":
Score: 14.8631, Doc ID: 474921, Image ID: 2, Caption: A child holding a flowered umbrella and petting a yak.
Score: 5.4041, Doc ID: 192463, Image ID: 33253, Caption: a close up of a child holding a closed umbrella
Score: 4.8333, Doc ID: 373329, Image ID: 8726, Caption: A child, wearing a cat costume and umbrella, stands before a brick building.
Score: 4.4001, Doc ID: 402111, Image ID: 7647, Caption: a woman and a child holding umbrellas and smiling
Score: 4.2001, Doc ID: 373406, Image ID: 5477, Caption: A black and white photo of a man sitting by the water holding an umbrella to give him shade.
Score: 4.0549, Doc ID: 268757, Image ID: 39202, Caption: A man holding a bottle and a group of people near an umbrella.
Score: 4.0296, Doc ID: 488669, Image ID: 6873, Caption: An adult standing holding surfboard and a child kneeling by water.
Score: 3.9733, Doc ID: 403240, Image ID: 31747, Caption: A man in shirt and tie holding an umbrella.
Score: 3.6131, Doc ID: 507682, Image ID: 6004, Caption: A child sitting on top of a chair holding a teddy bear.
Score: 3.5875, Doc ID: 184436, Image ID: 25158, Caption: A young child is holding a blue skateboard.

Search results for field "caption.bm25_0_75":
Score: 32.5340, Doc ID: 474921, Image ID: 2, Caption: A child holding a flowered umbrella and petting a yak.
Score: 11.7282, Doc ID: 192463, Image ID: 33253, Caption: a close up of a child holding a closed umbrella
Score: 10.4724, Doc ID: 373329, Image ID: 8726, Caption: A child, wearing a cat costume and umbrella, stands before a brick building.
Score: 9.1346, Doc ID: 373406, Image ID: 5477, Caption: A black and white photo of a man sitting by the water holding an umbrella to give him shade.
Score: 8.9925, Doc ID: 402111, Image ID: 7647, Caption: a woman and a child holding umbrellas and smiling
Score: 8.8651, Doc ID: 488669, Image ID: 6873, Caption: An adult standing holding surfboard and a child kneeling by water.
Score: 8.7412, Doc ID: 403240, Image ID: 31747, Caption: A man in shirt and tie holding an umbrella.
Score: 8.7412, Doc ID: 268757, Image ID: 39202, Caption: A man holding a bottle and a group of people near an umbrella.
Score: 7.7850, Doc ID: 507682, Image ID: 6004, Caption: A child sitting on top of a chair holding a teddy bear.
Score: 7.7850, Doc ID: 184436, Image ID: 25158, Caption: A young child is holding a blue skateboard.

## Semantic Text Search

TODO: upload so to encode only the inserted images

In [15]:
from sentence_transformers import SentenceTransformer
import numpy as np
import pandas as pd


df = ds.to_pandas()
#raw_captions = df['sentences'].apply(lambda x: x['raw']).head()

df = pd.DataFrame(
    {
        "sentid": df['sentences'].apply(lambda x: x['sentid']),
        "imgid": df['sentences'].apply(lambda x: x['imgid']),
        "raw": df['sentences'].apply(lambda x: x['raw']),
    }
).drop_duplicates(subset=['imgid'], keep='first').reset_index(drop=True)
df.head()

sbert_model = SentenceTransformer('all-mpnet-base-v2')
bge_model = SentenceTransformer('BAAI/bge-small-en-v1.5')
sbert_encoding = sbert_model.encode(df['raw'], show_progress_bar=True)
bge_encoding = bge_model.encode(df['raw'], show_progress_bar=True)

print("SBERT Encodings shape:", sbert_encoding.shape)
print("BGE Encodings shape:", bge_encoding.shape)

df['sbert_embedding'] = list(sbert_encoding)
df['bge_embedding'] = list(bge_encoding)

df.head()
df.to_parquet('coco_captions_embeddings.parquet', index=False)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

SBERT Encodings shape: (5000, 768)
BGE Encodings shape: (5000, 384)

In [16]:
df.head()

,sentid,imgid,raw,sbert_embedding,bge_embedding
0,474921,2,A child holding a flowered umbrella and pettin...,"[0.043276522, -0.07047357, 0.0053688735, 0.023...","[0.011913764, -0.0007062534, 0.08118155, -0.02..."
1,124166,15,A narrow kitchen filled with appliances and co...,"[-0.010408675, -0.054555293, -0.01693293, -0.0...","[0.016339002, 0.012613272, 0.043380924, -0.013..."
2,96821,36,A little girl holding a kitten next to a blue ...,"[0.028164648, 0.0203255, 0.018007534, -0.01604...","[0.04609613, 0.012474204, 0.047648523, 0.02186..."
3,204010,53,A toilet sitting in a bathroom next to a sink.,"[0.01762949, -0.0095861005, -0.035485506, -0.0...","[0.05711122, -0.045034394, 0.067034, -0.071054..."
4,444042,57,There are two sinks next to two mirrors.,"[0.046684165, -0.025488446, -0.02733047, -0.00...","[0.021507654, 0.023089329, 0.057892725, -0.022..."

## Update index

In [17]:
df = pd.read_parquet('coco_captions_embeddings.parquet')
df.head()

,sentid,imgid,raw,sbert_embedding,bge_embedding
0,474921,2,A child holding a flowered umbrella and pettin...,"[0.043276522, -0.07047357, 0.0053688735, 0.023...","[0.011913764, -0.0007062534, 0.08118155, -0.02..."
1,124166,15,A narrow kitchen filled with appliances and co...,"[-0.010408675, -0.054555293, -0.01693293, -0.0...","[0.016339002, 0.012613272, 0.043380924, -0.013..."
2,96821,36,A little girl holding a kitten next to a blue ...,"[0.028164648, 0.0203255, 0.018007534, -0.01604...","[0.04609613, 0.012474204, 0.047648523, 0.02186..."
3,204010,53,A toilet sitting in a bathroom next to a sink.,"[0.01762949, -0.0095861005, -0.035485506, -0.0...","[0.05711122, -0.045034394, 0.067034, -0.071054..."
4,444042,57,There are two sinks next to two mirrors.,"[0.046684165, -0.025488446, -0.02733047, -0.00...","[0.021507654, 0.023089329, 0.057892725, -0.022..."

In [18]:
def update_index(client, index_name, df):
    actions = []
    for i, row in df.iterrows():
        action = {
            "_op_type": "update",
            "_index": index_name,
            "_id": row['sentid'],
            "doc": {
                "SBERT_embedding": row['sbert_embedding'],
                "BGE_embedding": row['bge_embedding']
            }
        }
        actions.append(action)
        if len(actions) == 1000:
            helpers.bulk(client, actions)
            print(f"Updated {i+1} documents")
            actions = []
    if actions:
        helpers.bulk(client, actions)
        print(f"Updated {len(df)} documents in total")

In [19]:

update_index(client, index_name, df)

Updated 1000 documents
Updated 2000 documents
Updated 3000 documents
Updated 4000 documents
Updated 5000 documents

In [20]:
#query a random document to check if the update was successful
result = client.search(
    index=index_name,
    body={"query": {"match_all": {}}, "size": 1}
)
pp.pprint(result['hits']['hits'][0]['_source'])

{'BGE_embedding': [0.03406848,
                   0.03607354,
                   0.083689466,
                   -0.009539747,
                   -0.006600081,
                   -0.0013830524,
                   0.07237252,
                   0.033579133,
                   0.097500905,
                   0.018711755,
                   -0.035702437,
                   -0.020488936,
                   0.053530943,
                   0.066078424,
                   0.0044054026,
                   -0.008169162,
                   -0.009327146,
                   0.053750288,
                   -0.08079825,
                   -0.01815123,
                   0.14487408,
                   -0.04196044,
                   -0.003295689,
                   -0.051035877,
                   -0.025120702,
                   -0.019775096,
                   0.0059935725,
                   -0.015238627,
                   -0.017460197,
                   -0.09413924,
                   -0.042522144,
                   -0.006782912,
                   0.016646659,
                   -0.048374142,
                   0.092649594,
                   -0.04673144,
                   -0.057787377,
                   0.039107077,
                   -0.057417545,
                   0.0010254264,
                   0.015075977,
                   -0.0123663265,
                   -0.025998892,
                   -0.044231303,
                   -0.03245176,
                   0.0067201215,
                   0.002589819,
                   -0.028298322,
                   0.06398781,
                   -0.011713622,
                   0.08917652,
                   -0.02802469,
                   0.015773693,
                   0.038940478,
                   0.0009482743,
                   0.01055181,
                   0.074816674,
                   -0.025336865,
                   0.066347964,
                   0.015141628,
                   0.04972121,
                   0.022509538,
                   -0.08157209,
                   0.079630084,
                   0.034722593,
                   -0.054651346,
                   0.019444812,
                   -0.027411968,
                   0.075174674,
                   0.006077698,
                   0.011822221,
                   -0.010932987,
                   0.040140126,
                   0.030849949,
                   0.010189966,
                   -0.08955414,
                   0.026842583,
                   -0.0497076,
                   -0.06593168,
                   0.007676546,
                   -0.024053762,
                   0.027217312,
                   0.0072804806,
                   -0.035710257,
                   -0.002091123,
                   -0.029975515,
                   -0.0457998,
                   0.0204789,
                   0.013480506,
                   0.014329658,
                   -0.006489362,
                   -0.0069517754,
                   -0.06206063,
                   -0.016951237,
                   0.040141888,
                   -0.07070616,
                   -0.05259639,
                   -0.05193909,
                   0.040309053,
                   0.3008379,
                   -0.060589094,
                   -0.0142113585,
                   0.11761691,
                   -0.03164902,
                   0.0904962,
                   0.048170477,
                   0.048404153,
                   -0.019383945,
                   -0.018387709,
                   0.0031203069,
                   -0.048596483,
                   -0.043064438,
                   0.036831897,
                   0.008768554,
                   -0.033278883,
                   -0.024838177,
                   0.011516687,
                   0.0015356219,
                   0.011983502,
                   -0.04881613,
                   0.01835261,
                   0.010617303,
                   -0.021210514,
                   -0.036642782,
                   -0.0018219153,
                   0.036601916,
                   0.045556415,
                   0.027635068,
                   -0.047657322,
                   0.045276344,
                   -0.083940424,
                   -0.023374261,
                   0.055699095,
                   0.018586969,
                   0.003966404,
                   0.064535975,
                   0.07870536,
                   -0.0680632,
                   0.037226595,
                   -0.007856057,
                   -0.026884636,
                   -0.067289695,
                   0.014403795,
                   -0.09943343,
                   0.07162093,
                   0.053249013,
                   -0.015791388,
                   -0.0015520166,
                   -0.01682093,
                   0.004414907,
                   -0.02771105,
                   0.070733,
                   0.031140625,
                   -0.0061803586,
                   -0.042392906,
                   -0.010904759,
                   -0.04277689,
                   0.11713001,
                   0.01711605,
                   -0.009578045,
                   0.071575254,
                   -0.011526678,
                   -0.022387683,
                   0.004992327,
                   -0.03394958,
                   -0.07840396,
                   -0.034720097,
                   -0.037974574,
                   -0.03477963,
                   0.0029860311,
                   -0.004553161,
                   0.041715696,
                   -0.010836721,
                   0.046011418,
                   0.051406387,
                   -0.033836383,
                   0.005135087,
                   0.04909801,
                   0.061001703,
                   0.0360095,
                   -0.005341777,
                   0.0116944425,
                   -0.08397043,
                   0.03345704,
                   0.054679308,
                   -0.051753953,
                   0.012524361,
                   0.06813421,
                   0.017159935,
                   0.062672414,
                   0.031119972,
                   0.037553538,
                   -0.09191969,
                   0.04821767,
                   0.007630385,
                   0.00346085,
                   0.00766098,
                   -0.0057511586,
                   -0.11451916,
                   -0.0024652248,
                   0.04443576,
                   0.021508483,
                   -0.026274575,
                   -0.021374645,
                   0.039740477,
                   -0.020728176,
                   0.06192136,
                   0.018514888,
                   0.019515747,
                   -0.03221004,
                   -0.0042510023,
                   0.05651787,
                   0.068432786,
                   -0.0040859464,
                   0.051459562,
                   -0.011749943,
                   -0.010111238,
                   -0.017338993,
                   0.066924684,
                   -0.014657229,
                   0.030449014,
                   0.037706323,
                   -0.08910068,
                   -0.24093914,
                   0.04923118,
                   0.016861409,
                   -0.023827981,
                   0.0030699836,
                   0.0354933,
                   0.009968641,
                   -0.019934392,
                   0.033947304,
                   -0.03130312,
                   0.09701206,
                   0.0064179874,
                   -0.012690559,
                   0.06711116,
                   -0.022348555,
                   -0.034446042,
                   0.041188013,
                   0.05371839,
                   -0.036760528,
                   -0.02421768,
                   -0.011321882,
                   0.012747352,
                   0.078772016,
                   0.010438969,
                   0.012827347,
                   0.031920113,
                   0.1649082,
                   0.022530342,
                   -0.010417772,
                   -0.05207042,
                   0.030161211,
                   -0.046007276,
                   -0.022184964,
                   -0.08619116,
                   0.051495817,
                   0.100911655,
                   0.009736438,
                   0.021097116,
                   -0.06987019,
                   -0.022536758,
                   -0.004761851,
                   0.011402891,
                   -0.0025624842,
                   -0.014056636,
                   0.06228458,
                   0.019593192,
                   0.0026868072,
                   0.018732885,
                   -0.01628247,
                   -0.05284307,
                   0.035606056,
                   0.0012244233,
                   0.00783606,
                   0.03321348,
                   -0.031945284,
                   0.0011250438,
                   0.0324163,
                   -0.032220036,
                   -0.011475787,
                   -0.03543284,
                   -0.0137865925,
                   -0.048433647,
                   0.12057097,
                   -0.008574971,
                   -0.022331407,
                   0.004919187,
                   -0.061307024,
                   0.0052295774,
                   0.025271762,
                   -0.063795105,
                   -0.026371226,
                   0.031376168,
                   -0.049174678,
                   0.034013946,
                   0.009015003,
                   0.0020593058,
                   -0.014024126,
                   0.037571006,
                   0.034624275,
                   -0.027577505,
                   0.012534727,
                   -0.014526667,
                   0.014944787,
                   -0.014995192,
                   0.015795402,
                   -0.017268227,
                   -0.0011407508,
                   -0.0227764,
                   0.024064938,
                   -0.005678405,
                   0.00012261022,
                   0.021428362,
                   -0.04610255,
                   0.07297441,
                   0.0007546099,
                   -0.019994926,
                   -0.28191984,
                   -0.015698249,
                   -0.078977145,
                   -0.011983504,
                   -0.073230796,
                   -0.08868794,
                   -0.0344438,
                   0.07740278,
                   0.014269203,
                   -0.03518545,
                   0.051231742,
                   -0.007545028,
                   0.014343564,
                   -0.040001404,
                   0.022867821,
                   -0.066229336,
                   0.080885425,
                   0.00677611,
                   0.019462075,
                   -0.039531007,
                   0.010945704,
                   -0.08326122,
                   0.13292305,
                   -0.005257131,
                   -0.0033112143,
                   0.0013737144,
                   0.0079718,
                   -0.016043551,
                   -0.02486511,
                   0.01767895,
                   -0.061788905,
                   0.047947224,
                   0.0035366232,
                   0.012266726,
                   -0.004319538,
                   0.05102321,
                   0.028866097,
                   0.046707496,
                   -0.017810958,
                   -0.021202639,
                   -0.13144451,
                   -0.053790238,
                   -0.09157316,
                   -0.027886761,
                   0.026528595,
                   -0.09945958,
                   0.023895897,
                   -0.0005434927,
                   0.043256715,
                   -0.04354241,
                   0.053374205,
                   0.015495859,
                   -0.058208957,
                   -0.014352978,
                   -0.015199409,
                   0.00959234,
                   -0.11071461,
                   -0.040436845,
                   0.020682214,
                   -0.0034055964,
                   -0.045210037,
                   -0.004527217,
                   0.008144848,
                   -0.08754294,
                   -0.026135674],
 'SBERT_embedding': [0.00070872565,
                     0.020678177,
                     -0.046294134,
                     -0.009296951,
                     -0.033452146,
                     0.01818562,
                     0.012454375,
                     0.0048271082,
                     0.013310972,
                     -0.0155670075,
                     -0.022828482,
                     -0.13095237,
                     -0.046925146,
                     -0.0713513,
                     0.055610918,
                     -0.0093866,
                     0.025170894,
                     0.009698281,
                     -0.10784031,
                     -0.007793713,
                     -0.026343804,
                     -0.03450495,
                     -0.012414932,
                     0.016752327,
                     0.0031397059,
                     -0.022443486,
                     0.0011694528,
                     0.0044184043,
                     -0.056482356,
                     -0.04269955,
                     0.043328255,
                     0.08050364,
                     -0.01338814,
                     -0.014789324,
                     1.654358e-06,
                     -0.027311727,
                     0.0390439,
                     -0.019601516,
                     0.008598196,
                     -0.01001259,
                     0.0093949465,
                     0.029901817,
                     -0.021914138,
                     -0.0027474207,
                     0.012806752,
                     -0.03125249,
                     0.0042975796,
                     0.03000981,
                     -0.07474925,
                     0.011006796,
                     0.0075995224,
                     -0.064351335,
                     -0.04829979,
                     0.020283569,
                     0.0636895,
                     -0.028931266,
                     0.025940362,
                     -0.087001435,
                     -0.004886071,
                     -0.101099655,
                     0.048615467,
                     -0.0045235218,
                     -0.019101102,
                     -0.003458223,
                     -0.0151922805,
                     0.01764646,
                     -0.011193746,
                     0.025555324,
                     -0.043832887,
                     0.0049526417,
                     -0.055408884,
                     -0.0043792347,
                     0.014919589,
                     0.009311675,
                     -0.023585312,
                     -0.016264953,
                     -0.00639422,
                     0.015284862,
                     -0.003513651,
                     -0.018048897,
                     -0.12671019,
                     -0.006239871,
                     -0.023131395,
                     0.02286579,
                     0.038400065,
                     -0.0034257586,
                     0.019942183,
                     0.010559477,
                     -0.026752738,
                     0.0024378172,
                     -0.052938864,
                     -0.008269676,
                     0.01026904,
                     0.07920697,
                     0.023701847,
                     0.006098526,
                     0.0028540762,
                     -0.032572582,
                     0.0667667,
                     0.013431767,
                     0.056833602,
                     -0.0002477576,
                     -0.03307431,
                     0.011011368,
                     -0.009678344,
                     -0.008298356,
                     -0.009494231,
                     -0.09698534,
                     -0.025206419,
                     0.0059208088,
                     0.01739003,
                     0.013236361,
                     0.059296653,
                     -0.013870874,
                     0.008774603,
                     -0.032862615,
                     -0.0062755076,
                     0.042972114,
                     0.039792698,
                     0.062150914,
                     -0.051637627,
                     -0.015934126,
                     -0.008354527,
                     0.0016283183,
                     -0.0051852404,
                     -0.031126145,
                     0.014768689,
                     0.007440824,
                     -0.027651073,
                     0.008021619,
                     0.006118497,
                     -0.01004572,
                     -0.01876433,
                     -0.0072883773,
                     -0.047669627,
                     0.072539024,
                     0.043218914,
                     0.024060074,
                     0.043226663,
                     0.020837491,
                     -0.003574403,
                     0.021919323,
                     0.019602893,
                     0.037312776,
                     -0.010348397,
                     -0.032019936,
                     -0.014596905,
                     0.02120376,
                     0.00332448,
                     -0.01421002,
                     0.059958834,
                     -0.007643034,
                     0.038705453,
                     0.007265853,
                     0.013811152,
                     0.024673546,
                     -0.02062403,
                     -0.060712256,
                     0.011124889,
                     0.032239888,
                     0.008559377,
                     -0.03555542,
                     0.045605656,
                     -0.028772974,
                     -0.00806827,
                     -0.04447131,
                     0.11808566,
                     -0.0015389305,
                     0.09014034,
                     -0.028618515,
                     -0.033938788,
                     -0.014196097,
                     0.031948447,
                     0.016823083,
                     -0.052167796,
                     0.028843861,
                     -0.0024594765,
                     0.012243575,
                     -0.0045623523,
                     -0.009610384,
                     0.025987713,
                     0.042531617,
                     -0.009043471,
                     0.014975151,
                     0.07357385,
                     0.017772553,
                     -0.007005169,
                     0.07388225,
                     -0.024593582,
                     0.031979155,
                     -0.027411059,
                     0.008320593,
                     -0.029346164,
                     -0.023555705,
                     0.037210252,
                     -0.018212521,
                     -0.017117236,
                     0.04548969,
                     0.0657831,
                     -0.009711184,
                     0.024322864,
                     -0.03507918,
                     0.10482868,
                     0.14988248,
                     -0.041929066,
                     -0.03530101,
                     0.06517587,
                     0.012350887,
                     -0.0050973203,
                     0.001323352,
                     0.01014001,
                     0.014831289,
                     0.018357549,
                     -0.011786492,
                     -0.0006892617,
                     -0.04506876,
                     0.03114284,
                     0.04290215,
                     0.015966529,
                     -0.037816357,

In [ ]:
client.indices.close(index=index_name)

{'acknowledged': True,
 'shards_acknowledged': True,
 'indices': {'uservl07_project': {'closed': True}}}